// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// InputSpec request spec specifying client identifier and count of uuids needed
// swagger:model input_spec
type InputSpec struct {

	// client identifier
	ClientIdentifier string `json:"client_identifier,omitempty"`

	// number of uuids needed
	Count int64 `json:"count,omitempty"`
}

// Validate validates this input spec
func (m *InputSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InputSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InputSpec) UnmarshalBinary(b []byte) error {
	var res InputSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
