// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// OutputSpec returned uuids
// swagger:model output_spec
type OutputSpec struct {

	// client identifier
	ClientIdentifier string `json:"client_identifier,omitempty"`

	// number of uuids needed
	Count int64 `json:"count,omitempty"`

	// array of returned uuids
	UUIDList []string `json:"uuid_list"`
}

// Validate validates this output spec
func (m *OutputSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OutputSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OutputSpec) UnmarshalBinary(b []byte) error {
	var res OutputSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
